In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([-1.44626798,  0.8613908 , -0.29945123,  1.49268768,  1.67166043,
        1.94940561,  1.47789803,  0.13886747, -1.68636497,  0.21411992,
       -0.4780682 ,  0.1152981 , -0.18297998, -1.77691557, -0.64747826,
       -0.28626064,  0.5399083 ,  0.61535262,  0.51101102, -0.13690606,
        0.24901019, -0.76103094, -0.51814795,  0.02387966,  0.53154799,
        0.52897351,  0.25127243,  0.06006454, -0.47516342,  0.61643149,
        0.96674528,  0.66321062,  1.41082295, -0.49538372, -0.09225411,
        0.30012081,  0.4411283 ,  0.40946564, -0.02990879,  1.20981444,
        0.54239323,  1.7683555 ,  1.59798687,  0.94413416, -0.59313572,
       -0.83363629, -0.65201594, -1.38871921,  1.23894941,  0.28421897,
        0.08318617,  1.20907634, -0.5645378 ,  0.32135366,  1.35712256,
        0.72296953,  0.7334624 ,  0.25018915,  2.65569544,  1.55375166,
        0.57657574, -1.12154176,  1.74445041, -1.01104252, -1.80255904,
        1.09750977,  0.86911154,  1.56307137, -1.4331837 , -0.95

In [4]:
A = 10*A + 50

In [5]:
A

array([35.53732015, 58.61390805, 47.00548774, 64.9268768 , 66.71660431,
       69.49405606, 64.77898028, 51.38867473, 33.13635034, 52.14119921,
       45.21931796, 51.15298099, 48.17020021, 32.23084428, 43.52521744,
       47.13739363, 55.399083  , 56.15352625, 55.11011017, 48.63093944,
       52.49010188, 42.38969061, 44.81852051, 50.23879658, 55.31547995,
       55.28973505, 52.51272432, 50.60064535, 45.24836578, 56.16431491,
       59.66745277, 56.63210616, 64.10822947, 45.04616276, 49.07745889,
       53.00120812, 54.41128298, 54.09465642, 49.70091213, 62.09814444,
       55.42393229, 67.68355504, 65.97986873, 59.4413416 , 44.06864282,
       41.66363706, 43.4798406 , 36.11280786, 62.38949407, 52.84218967,
       50.83186173, 62.09076344, 44.35462195, 53.21353662, 63.57122558,
       57.22969533, 57.33462396, 52.50189145, 76.55695439, 65.53751657,
       55.76575738, 38.78458238, 67.44450412, 39.88957477, 31.97440955,
       60.97509769, 58.69111539, 65.63071373, 35.66816297, 40.46

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5,20)

In [8]:
A

array([[35.53732015, 58.61390805, 47.00548774, 64.9268768 , 66.71660431,
        69.49405606, 64.77898028, 51.38867473, 33.13635034, 52.14119921,
        45.21931796, 51.15298099, 48.17020021, 32.23084428, 43.52521744,
        47.13739363, 55.399083  , 56.15352625, 55.11011017, 48.63093944],
       [52.49010188, 42.38969061, 44.81852051, 50.23879658, 55.31547995,
        55.28973505, 52.51272432, 50.60064535, 45.24836578, 56.16431491,
        59.66745277, 56.63210616, 64.10822947, 45.04616276, 49.07745889,
        53.00120812, 54.41128298, 54.09465642, 49.70091213, 62.09814444],
       [55.42393229, 67.68355504, 65.97986873, 59.4413416 , 44.06864282,
        41.66363706, 43.4798406 , 36.11280786, 62.38949407, 52.84218967,
        50.83186173, 62.09076344, 44.35462195, 53.21353662, 63.57122558,
        57.22969533, 57.33462396, 52.50189145, 76.55695439, 65.53751657],
       [55.76575738, 38.78458238, 67.44450412, 39.88957477, 31.97440955,
        60.97509769, 58.69111539, 65.63071373, 3

In [9]:
A.reshape(100,1)

array([[35.53732015],
       [58.61390805],
       [47.00548774],
       [64.9268768 ],
       [66.71660431],
       [69.49405606],
       [64.77898028],
       [51.38867473],
       [33.13635034],
       [52.14119921],
       [45.21931796],
       [51.15298099],
       [48.17020021],
       [32.23084428],
       [43.52521744],
       [47.13739363],
       [55.399083  ],
       [56.15352625],
       [55.11011017],
       [48.63093944],
       [52.49010188],
       [42.38969061],
       [44.81852051],
       [50.23879658],
       [55.31547995],
       [55.28973505],
       [52.51272432],
       [50.60064535],
       [45.24836578],
       [56.16431491],
       [59.66745277],
       [56.63210616],
       [64.10822947],
       [45.04616276],
       [49.07745889],
       [53.00120812],
       [54.41128298],
       [54.09465642],
       [49.70091213],
       [62.09814444],
       [55.42393229],
       [67.68355504],
       [65.97986873],
       [59.4413416 ],
       [44.06864282],
       [41

In [10]:
A

array([[35.53732015, 58.61390805, 47.00548774, 64.9268768 , 66.71660431,
        69.49405606, 64.77898028, 51.38867473, 33.13635034, 52.14119921,
        45.21931796, 51.15298099, 48.17020021, 32.23084428, 43.52521744,
        47.13739363, 55.399083  , 56.15352625, 55.11011017, 48.63093944],
       [52.49010188, 42.38969061, 44.81852051, 50.23879658, 55.31547995,
        55.28973505, 52.51272432, 50.60064535, 45.24836578, 56.16431491,
        59.66745277, 56.63210616, 64.10822947, 45.04616276, 49.07745889,
        53.00120812, 54.41128298, 54.09465642, 49.70091213, 62.09814444],
       [55.42393229, 67.68355504, 65.97986873, 59.4413416 , 44.06864282,
        41.66363706, 43.4798406 , 36.11280786, 62.38949407, 52.84218967,
        50.83186173, 62.09076344, 44.35462195, 53.21353662, 63.57122558,
        57.22969533, 57.33462396, 52.50189145, 76.55695439, 65.53751657],
       [55.76575738, 38.78458238, 67.44450412, 39.88957477, 31.97440955,
        60.97509769, 58.69111539, 65.63071373, 3

In [11]:
A = A.reshape(100,1)

In [12]:
A

array([[35.53732015],
       [58.61390805],
       [47.00548774],
       [64.9268768 ],
       [66.71660431],
       [69.49405606],
       [64.77898028],
       [51.38867473],
       [33.13635034],
       [52.14119921],
       [45.21931796],
       [51.15298099],
       [48.17020021],
       [32.23084428],
       [43.52521744],
       [47.13739363],
       [55.399083  ],
       [56.15352625],
       [55.11011017],
       [48.63093944],
       [52.49010188],
       [42.38969061],
       [44.81852051],
       [50.23879658],
       [55.31547995],
       [55.28973505],
       [52.51272432],
       [50.60064535],
       [45.24836578],
       [56.16431491],
       [59.66745277],
       [56.63210616],
       [64.10822947],
       [45.04616276],
       [49.07745889],
       [53.00120812],
       [54.41128298],
       [54.09465642],
       [49.70091213],
       [62.09814444],
       [55.42393229],
       [67.68355504],
       [65.97986873],
       [59.4413416 ],
       [44.06864282],
       [41